# Generated by Django 5.2.1 on 2025-05-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="telegram_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
